# Generated by Django 2.2.7 on 2019-11-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_owner', models.CharField(max_length=75)),
                ('acc_number', models.TextField()),
                ('acc_balance', models.TextField()),
            ],
            options={
                'db_table': 'bank_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_symbol', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=1000)),
                ('company_description', models.CharField(max_length=2500)),
                ('company_employees', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=75)),
                ('company_zip', models.CharField(max_length=10)),
                ('company_country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringBuy',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('rec_user_id', models.CharField(max_length=50)),
                ('rec_symbol', models.CharField(max_length=50)),
                ('rec_interval', models.CharField(max_length=50)),
                ('rec_start_timestamp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recurring_buy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_user', models.CharField(max_length=50)),
                ('stock_symbol', models.CharField(max_length=50)),
                ('stock_buy_price', models.CharField(max_length=50)),
                ('stock_buy_timestamp', models.CharField(max_length=50)),
                ('stock_count', models.IntegerField()),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_user', models.CharField(max_length=50)),
                ('transaction_timestamp', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_symbol', models.CharField(max_length=50)),
                ('transaction_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=50)),
                ('user_lname', models.CharField(max_length=50)),
                ('user_ssn', models.TextField()),
                ('user_address', models.CharField(max_length=75)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
